summary: Organise livestream scenes

priority: should

component: Competition

milestone: $SRYYYY Competition Prep

area-owner: livestream

description: >-
  The livestream requires a number of different scenes and views, made up of
  static images, video feeds, overlays etc.

  Most of the assets have already been created, but some may require updating
  or new ones created

  See https://studentrobotics.org/runbook/competition/livestream/scenes/.

dependencies:
  - comp/livestream/plan-video-feeds
