summary: Show the live stream within the venue

priority: should

component: Competition

milestone: $SRYYYY Competition

area-owner: livestream

description: >-
  We should ensure the live stream of the competition is viewable within
  the venue. This enables everyone to see matches without actually being
  arena-side.

  In the past the display has included a split-screen view of all the
  arenas which most people liked. It would be good to do this again.

dependencies:
  - comp/livestream/main
