summary: Build the arenas

component: Arena

milestone: $SRYYYY Competition

area-owner: event-logistics

description: >-
    Build some arenas for the games.

    This covers the physical construction of the arenas, including props
    needed for the game and markings for the start-position of any
    which are moveable. The arenas should also be marked so it's clear
    which is which.

dependencies:
    - comp/arena/carpet
    - comp/arena/tape
    - comp/arena/network
    - comp/arena/power
    - comp/arena/screens
    - comp/arena/tools
